import { ModeToggle } from "@/components/ModeToggle";
import SearchBox from "@/components/SearchBox";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";
import MainLayout from "@/components/MainLayout";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="bg-secondary flex flex-col min-h-screen">
            {/* top nav */}
            <div className="sticky top-0 flex justify-between px-[calc(1%+10px)] py-4 shadow-md bg-background z-50">
              <div className="grid place-content-center">
                <Link
                  href="/"
                  className="text-2xl font-semibold tracking-tight"
                >
                  Artwork
                </Link>
              </div>
              <div className="grid place-content-center">
                <Suspense>
                  <SearchBox />
                </Suspense>
              </div>
              <div className="flex items-center gap-x-1">
                <Button variant="link" asChild>
                  <Link href="/login">Login</Link>
                </Button>
                <ModeToggle />
              </div>
            </div>

            <MainLayout>{children}</MainLayout>
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
